package gui;

import client.RequestSender;
import org.apache.commons.codec.digest.DigestUtils;
import resources.ResourceController;
import tools.Message;
import tools.Request;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class RegistrationGUI {

    private JPanel mainPanel;
    private JTextField loginField;
    private JPasswordField passwordField;
    private JButton loginButton;
    private JLabel messageLabel;
    private JPanel registrationPanel;
    private JPanel messagePanel;
    private JButton backButton;
    private JPanel userPanel;
    private JComboBox languageComboBox;
    private RequestSender requestSender;
    private boolean flag = true;
    private ResourceController resourceController;
    private String[] languages = {"Russian", "Portuguese", "Albanian", "English (Canada)"};

    public RegistrationGUI(RequestSender requestSender, ResourceController resourceController) {
        this.requestSender = requestSender;
        this.resourceController = resourceController;
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setBackground(new Color(-13025985));
        mainPanel.setPreferredSize(new Dimension(700, 450));
        messagePanel = new JPanel();
        messagePanel.setLayout(new GridBagLayout());
        messagePanel.setBackground(new Color(-13025985));
        messagePanel.setPreferredSize(new Dimension(540, 40));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(messagePanel, gbc);
        Font messageLabelFont = this.$$$getFont$$$("Franklin Gothic Demi", Font.PLAIN, 24, messageLabel.getFont());
        if (messageLabelFont != null) messageLabel.setFont(messageLabelFont);
        messageLabel.setForeground(new Color(-1));
        messageLabel.setHorizontalAlignment(0);
        messageLabel.setHorizontalTextPosition(0);
        messageLabel.setPreferredSize(new Dimension(540, 30));
        messageLabel.setText("Авторизация");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        messagePanel.add(messageLabel, gbc);
        registrationPanel = new JPanel();
        registrationPanel.setLayout(new GridBagLayout());
        registrationPanel.setBackground(new Color(-13025985));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 105, 0);
        mainPanel.add(registrationPanel, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-13025985));
        panel1.setPreferredSize(new Dimension(400, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 0, 0);
        registrationPanel.add(panel1, gbc);
        loginField = new JTextField();
        loginField.setBackground(new Color(-13025985));
        loginField.setCaretColor(new Color(-1));
        loginField.setDisabledTextColor(new Color(-1));
        loginField.setEditable(true);
        loginField.setEnabled(true);
        loginField.setForeground(new Color(-1));
        loginField.setPreferredSize(new Dimension(180, 30));
        loginField.setRequestFocusEnabled(true);
        loginField.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(loginField, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setBackground(new Color(-13025985));
        panel2.setPreferredSize(new Dimension(400, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(2, 0, 0, 0);
        registrationPanel.add(panel2, gbc);
        passwordField = new JPasswordField();
        passwordField.setBackground(new Color(-13025985));
        passwordField.setCaretColor(new Color(-1));
        passwordField.setDisabledTextColor(new Color(-1));
        passwordField.setForeground(new Color(-1));
        passwordField.setPreferredSize(new Dimension(180, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(passwordField, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setBackground(new Color(-13025985));
        panel3.setPreferredSize(new Dimension(400, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 0, 0);
        registrationPanel.add(panel3, gbc);
        loginButton.setActionCommand("");
        loginButton.setAlignmentX(0.5f);
        loginButton.setAlignmentY(0.5f);
        loginButton.setAutoscrolls(false);
        loginButton.setBackground(new Color(-13025985));
        loginButton.setBorderPainted(true);
        loginButton.setFocusPainted(false);
        Font loginButtonFont = this.$$$getFont$$$("Franklin Gothic Demi", Font.PLAIN, 18, loginButton.getFont());
        if (loginButtonFont != null) loginButton.setFont(loginButtonFont);
        loginButton.setForeground(new Color(-1));
        loginButton.setPreferredSize(new Dimension(180, 30));
        loginButton.setText("Регистрация");
        loginButton.putClientProperty("hideActionText", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(loginButton, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setBackground(new Color(-13025985));
        panel4.setPreferredSize(new Dimension(400, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(20, 0, 0, 0);
        registrationPanel.add(panel4, gbc);
        backButton.setActionCommand("");
        backButton.setAlignmentX(0.5f);
        backButton.setAlignmentY(0.5f);
        backButton.setAutoscrolls(false);
        backButton.setBackground(new Color(-13025985));
        backButton.setBorderPainted(true);
        backButton.setFocusPainted(false);
        Font backButtonFont = this.$$$getFont$$$("Franklin Gothic Demi", Font.PLAIN, 18, backButton.getFont());
        if (backButtonFont != null) backButton.setFont(backButtonFont);
        backButton.setForeground(new Color(-1));
        backButton.setPreferredSize(new Dimension(180, 30));
        backButton.setText("Назад");
        backButton.putClientProperty("hideActionText", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(backButton, gbc);
        userPanel = new JPanel();
        userPanel.setLayout(new GridBagLayout());
        userPanel.setAutoscrolls(false);
        userPanel.setBackground(new Color(-13025985));
        userPanel.setMinimumSize(new Dimension(537, 55));
        userPanel.setPreferredSize(new Dimension(600, 55));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 50, 0);
        mainPanel.add(userPanel, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel5.setBackground(new Color(-13025985));
        panel5.setPreferredSize(new Dimension(300, 55));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 0, 300);
        userPanel.add(panel5, gbc);
        languageComboBox.setBackground(new Color(-13025985));
        languageComboBox.setForeground(new Color(-1));
        languageComboBox.setOpaque(true);
        languageComboBox.setPreferredSize(new Dimension(150, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 0, 0, 150);
        panel5.add(languageComboBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private Timer timer;

    public void drawMessages() {
        messageLabel.setText(resourceController.getMainResourceBundle().getString("Авторизация"));
        loginButton.setText(resourceController.getMainResourceBundle().getString("Регистрация"));
        backButton.setText(resourceController.getMainResourceBundle().getString("Назад"));
    }

    private void createUIComponents() {
        loginButton = new JButton();
        backButton = new JButton();
        messageLabel = new JLabel();

        languageComboBox = new JComboBox(languages);
        languageComboBox.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                resourceController.setMainResourceBundleByIndex(languageComboBox.getSelectedIndex());
                drawMessages();
            }
        });
        languageComboBox.setSelectedIndex(resourceController.getSelectedLanguage());

        loginButton.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String login = loginField.getText();
                char[] passwordChars = passwordField.getPassword();
                if (login.equals("") || String.valueOf(passwordChars).equals("")) {
                    messageLabel.setText(resourceController.getMainResourceBundle().getString("Введите логин и пароль!"));
                } else {
                    loginField.setText("");
                    passwordField.setText("");
                    String password = DigestUtils.sha1Hex(String.valueOf(passwordChars));
                    Request request = new Request("auth", login, password, false, resourceController.getMainResourceBundle().getBaseBundleName());
                    requestSender.sendRequest(request);
                    Message message = requestSender.getAnswer();
                    messageLabel.setText(message.getMessage());
                    if (message.getAuthorizationCondition() == 0) {
                        registrationPanel.setVisible(false);
                        timer = new Timer(1000, new AbstractAction() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                messagePanel.setVisible(false);
                                mainPanel.removeAll();
                                MainGUI mainGUI = new MainGUI(requestSender, login, password, false, resourceController);
                                mainGUI.drawMessages();
                                mainGUI.setUserName();
                                mainPanel.add(mainGUI.$$$getRootComponent$$$());
                                timer.stop();
                            }
                        });
                        timer.start();
                    }
                }
            }
        });
        backButton.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                messagePanel.setVisible(false);
                registrationPanel.setVisible(false);
                mainPanel.removeAll();
                EnterGUI enterGUI = new EnterGUI(requestSender, resourceController);
                enterGUI.drawMessages();
                mainPanel.add(enterGUI.$$$getRootComponent$$$());
            }
        });
    }
}
